### PR TITLE
Added .gitignore files and removed unused .cvsignore files.

### PR DESCRIPTION
**Pull request by raeburn**
The contents aren't identical because of different semantics, changes in what files are generated, etc.

### CODE REVIEW

**Comment by C2Redhat** [comment]
The .gitignore files look good to be but should removing .cvsignore be one commit and adding .gitignore be another?

**Comment by raeburn** [comment]
> The .gitignore files look good to be but should removing .cvsignore be one commit and adding .gitignore be another?

I think it's reasonable to do as one as it's more or less updating the ignore-list functionality from CVS to git. I could make them two separate commits if you think that's clearer.

**Comment by C2Redhat** [comment]
Yes, please.  If it is not too much work.  Thanks!

**Review by C2Redhat — APPROVED** [review]
yay

**Pull request merged**
