### PR TITLE
Restore <5.15 kernels support

### PR DESCRIPTION
**Pull request by tigerblue77**
Hello @rhawalsh ,

Following our mail discussion, I reopen [this pull request](https://github.com/dm-vdo/kvdo/pull/52/files) in the development repository.

Linked to [this issue](https://github.com/dm-vdo/kvdo/issues/49). This code portion is needed for current Debian stable version (11.3) which uses 5.10 linux kernel. Support was dropped [in this commit](https://github.com/dm-vdo/kvdo/commit/819203a11871718d4551f23b3854457da5f267a8).

Feel free to close quoted issue/pull request once merged :)

### CODE REVIEW

**Review by sweettea — APPROVED** [review]

**Comment by rhawalsh** [comment]
Hi @tigerblue77 ,

Thank you for moving the PR over to this project.  In general, we need to figure out what our policy is going to be with regard to older kernel support.  Since this project is ultimately directed toward our mainline kernel contribution, every addition of an #ifdef for an older kernel must be removed.  Also over the years, I've seen some messy #ifdef's that have added quite a bit of complication to understand what's going on in certain areas.

I think, since this change is just restoring something that we previously had, we can probably pick this one back up.  But for anyone else looking in the future, I don't want it to look like we're just open to pulling in a ton of #ifdef's for older kernels.

There is also a testing component of this (and any other change along these lines) that we can't guarantee will continue to work at all times.  So if you want it to continue to work in the future, it's important to test it yourself.  We will have the infrastructure to run our check-in tests in place soon which will at least ensure that contributions such as this one do not break our existing environment.

Please give me some time to incorporate this into our tree with some testing.  I'll report back when it's ready.  Probably be somewhere around Tuesday or Wednesday this week when other members of the team are online.

**Comment by tigerblue77** [comment]
Hi @rhawalsh,

Thank you for taking the time to reply.

It's extremely clear and I can't agree more with your philosophy on #ifndef. However, I propose this PR because I'm using the latest stable version of Debian (bullseye / 11.4), with the officially provided kernel (5.10.x): https://packages.debian.org/bullseye/linux-image-amd64

I think I understand in your message that it is not the same version as the current stable kernel of RHEL. However, Debian is not marginal in the Linux world and I think that the kvdo module must be and remain compatible :)

Maybe there is a better fix than restoring those #ifndef? I have no time at all to study your code to propose a solution but I know you will make the right technical choice :)

**Comment by tigerblue77** [comment]
Hello @rhawalsh,
Hope you're doing well. Any news on this pull request ? :)

**Comment by rhawalsh** [comment]
Hi @tigerblue77 I'm hoping to work this into this repo at some point tomorrow.

**Comment by tigerblue77** [comment]
Hello @rhawalsh, I'm sorry I miss clicked on "sync fork" on my repository and that thrown away my edits and broken this pull request... What a shame. It's very late here and I'm too tired to check it now. Sorry for it, I hope I didn't lose the changes. Don't hesitate to tell me if I can rollback this or if I have to reopen a PR with the changes... Thanks in advance

**Comment by tigerblue77** [comment]
My changes were the same as [here](https://github.com/dm-vdo/kvdo/pull/52/files). Thanks for having a look! Have a good day Andy

**Comment by rhawalsh** [comment]
Hi @tigerblue77 No worries!  Since it's re-doing a change that we had previously, we still have the code in several places. :)

When you're ready to work on the iowait problems, I would suggest raising an email to vdo-devel@redhat.com or opening a new issue so we can focus on them without distractions of other things going on.

**Pull request closed without merging**
