### PR TITLE
dm vdo: add "funnel-" filename prefix to funnel-queue based sources

### PR DESCRIPTION
**Pull request by C2Redhat**
Implement funnel prefix to request-queue.[ch] and work-queue.[c] changes from linux-dm.

### CODE REVIEW

**Comment by lorelei-sakai** [comment]
Generally looks good. The #include lists and Makefile file lists should be alphabetized, though.

**Review by rhawalsh — CHANGES_REQUESTED** [review]
Before this can be merged, I think commit 0a7e110a235bb33193a56ec7cd01470082429bd4 should be removed from the list.

**Review by rhawalsh — DISMISSED** [review]
Extraneous comment.  Please resolve/disregard this one.

**Comment by raeburn** [comment]
Also manifest file lists, etc...all previously alphabetical file lists should be kept alphabetical.

**Comment by C2Redhat** [comment]
I have implemented all the changes, alphabetized all the files and proper commit sequence.

**Pull request merged**
